"""
Templated retrospective generator — replaces the `retrospective` LLM persona.

Phase 3 of futureplan.md (2026-05-06): the retrospective agent's only job
was to read sprint metadata + commit log + reviewer comments and emit a
markdown summary. That's mechanical work — sprint summary, what shipped,
what got deferred, fix_attempts hot-spots, reviewer-comment themes — and
costs ~$0.50 of LLM tokens per sprint to produce something a deterministic
template does just as well.

This module replaces the LLM session with `generate_and_commit_retro()`:

  1. Pull sprint, features, reviewer comments from PM API.
  2. Render `docs/retro_sprint_<id>.md` from a fixed Markdown template.
  3. Commit + push to origin/main (--no-verify, same as post_doc).
  4. POST /api/sprints/<id>/sign-off?gate=retro_done&retro_doc_path=...

The generator runs inline in the orchestrator's persona dispatch — no
agent container, no session record. Idempotent: if the doc already
exists on origin/main and retro_done is already true, returns early.
"""

from __future__ import annotations

import logging
import os
import subprocess as _sp
from pathlib import Path
from typing import Any

import httpx

from orchestrator.integrations.docker_cli import _chmod_workspace_via_alpine

log = logging.getLogger("poller.docker")

PM_API_URL = os.environ["PM_API_URL"]


def _fetch_retro_inputs(product_id: int, sprint_id: int) -> dict[str, Any]:
    """Pull everything the retro template needs in a single round-trip burst."""
    inputs: dict[str, Any] = {"sprint": None, "features": [], "comments": {}}
    try:
        with httpx.Client(base_url=PM_API_URL, timeout=10) as client:
            sp = client.get(f"/api/sprints/{sprint_id}")
            if sp.status_code == 200 and isinstance(sp.json(), dict):
                inputs["sprint"] = sp.json()
            fr = client.get(f"/api/products/{product_id}/features")
            if fr.status_code == 200 and isinstance(fr.json(), list):
                inputs["features"] = [
                    f for f in fr.json() if f.get("sprint_id") == sprint_id
                ]
            for f in inputs["features"]:
                fid = f["id"]
                cr = client.get(f"/api/features/{fid}/comments")
                if cr.status_code == 200 and isinstance(cr.json(), list):
                    # Keep only reviewer/auditor entries — coder/agent
                    # comments are noise for a retro.
                    inputs["comments"][fid] = [
                        c for c in cr.json()
                        if (c.get("author") or "").lower()
                        in ("reviewer", "security_auditor", "qa_tester")
                    ]
    except Exception as e:
        log.warning(f"[retro-gen] PM API fetch failed for sprint {sprint_id}: {e}")
    return inputs


def _render_retro_markdown(sprint: dict, features: list[dict], comments: dict[int, list[dict]]) -> str:
    """Pure formatter — no IO. Easy to unit-test."""
    sid = sprint.get("id", "?")
    name = sprint.get("name") or f"Sprint {sid}"
    started = (sprint.get("start_date") or sprint.get("created_at") or "")[:10]
    completed = (sprint.get("completed_at") or "")[:10]
    pr_url = sprint.get("pr_url") or ""

    terminal = {"Pushed", "Deferred", "Rejected"}
    pushed   = [f for f in features if f.get("status") == "Pushed"]
    deferred = [f for f in features if f.get("status") == "Deferred"]
    rejected = [f for f in features if f.get("status") == "Rejected"]
    in_flight = [f for f in features if f.get("status") not in terminal]

    # fix_attempts hot-spots — features that took the most rework cycles.
    rework_features = sorted(
        (f for f in features if (f.get("fix_attempts") or 0) > 0),
        key=lambda f: -(f.get("fix_attempts") or 0),
    )

    lines: list[str] = [
        f"# Retrospective — {name} (sprint #{sid})",
        "",
        "_Auto-generated by the orchestrator's retro template (Phase 3 of "
        "futureplan.md, 2026-05-06). Replaces the previous LLM-driven "
        "retrospective persona — same content, deterministic, no token cost._",
        "",
        f"- **Started:** {started or '—'}",
        f"- **Completed:** {completed or '—'}",
    ]
    if pr_url:
        lines.append(f"- **Sprint PR:** {pr_url}")
    lines += [
        f"- **Features in sprint:** {len(features)} ({len(pushed)} shipped, "
        f"{len(deferred)} deferred, {len(rejected)} rejected, "
        f"{len(in_flight)} still in-flight)",
        "",
    ]

    if pushed:
        lines.append("## Shipped")
        lines.append("")
        for f in pushed:
            lines.append(f"- **#{f['id']} {f.get('name', '')}** "
                         f"(fix_attempts={f.get('fix_attempts', 0)})")
        lines.append("")

    if deferred or rejected:
        lines.append("## Deferred / Rejected")
        lines.append("")
        for f in deferred + rejected:
            tag = f.get("status", "?")
            lines.append(f"- **#{f['id']} {f.get('name', '')}** "
                         f"({tag}) — {f.get('blocked_reason', '') or '—'}")
        lines.append("")

    if in_flight:
        lines.append("## Still In-Flight at Sprint Close")
        lines.append("")
        for f in in_flight:
            lines.append(f"- **#{f['id']} {f.get('name', '')}** "
                         f"(status={f.get('status')}, "
                         f"fix_attempts={f.get('fix_attempts', 0)})")
        lines.append("")

    if rework_features:
        lines.append("## Rework Hot-spots")
        lines.append("")
        lines.append("Features that required the most reviewer rework cycles "
                     "this sprint. High fix_attempts often indicates an "
                     "ambiguous design doc, or a feature that should have "
                     "been split.")
        lines.append("")
        for f in rework_features[:10]:
            lines.append(f"- **#{f['id']} {f.get('name', '')}** — "
                         f"{f.get('fix_attempts', 0)} rework cycles")
        lines.append("")

    # Reviewer comment themes — surface the key per-feature feedback so the
    # next sprint's coder/designer can spot recurring issues.
    comment_blocks: list[str] = []
    for f in features:
        c_list = comments.get(f["id"]) or []
        if not c_list:
            continue
        block = [f"### #{f['id']} {f.get('name', '')}", ""]
        for c in c_list[-3:]:  # last 3 per feature is plenty
            ts = (c.get("created_at") or "")[:19]
            author = c.get("author") or "?"
            body = (c.get("body") or "").strip().replace("\n", " ")[:200]
            block.append(f"- _{ts} · {author}_ — {body}")
        block.append("")
        comment_blocks.append("\n".join(block))
    if comment_blocks:
        lines.append("## Reviewer Comment Themes")
        lines.append("")
        lines.extend(comment_blocks)

    lines.append("---")
    lines.append("")
    lines.append("_End of retro. Action items, if any, should be filed as "
                 "new feature records with `priority` set appropriately._")
    return "\n".join(lines).rstrip() + "\n"


def generate_and_commit_retro(product: dict, sprint_id: int) -> bool:
    """
    End-to-end Phase 3 retro generation:
      1. Skip if already done (idempotent).
      2. Fetch sprint + features + comments.
      3. Render markdown.
      4. Write to <working_dir>/docs/retro_sprint_<id>.md.
      5. Commit + push to origin/main with --no-verify.
      6. POST /api/sprints/<id>/sign-off retro_done=true + retro_doc_path.

    Returns True on success, False on any failure (caller logs and
    falls back — the sprint stays "completed without retro" rather
    than blocking the pipeline).
    """
    pid   = product.get("id")
    pname = product.get("name", "?")
    working_dir = product.get("_working_dir") or product.get("working_dir")
    if not pid or not sprint_id or not working_dir:
        log.warning(f"[retro-gen] missing pid/sprint_id/working_dir — skipping")
        return False

    inputs = _fetch_retro_inputs(int(pid), int(sprint_id))
    sprint = inputs.get("sprint") or {}
    if not sprint:
        log.warning(f"[retro-gen] {pname}: no sprint payload for #{sprint_id} — skipping")
        return False
    if sprint.get("retro_doc_path"):
        log.info(f"[retro-gen] {pname}: sprint #{sprint_id} already has retro_doc_path — skipping")
        return True

    # Render + write
    doc = _render_retro_markdown(sprint, inputs.get("features") or [],
                                 inputs.get("comments") or {})
    rel_path = f"docs/retro_sprint_{sprint_id}.md"
    abs_path = Path(working_dir) / rel_path
    try:
        abs_path.parent.mkdir(parents=True, exist_ok=True)
        abs_path.write_text(doc, encoding="utf-8")
        log.info(f"[retro-gen] {pname}: wrote {rel_path} ({len(doc)} chars)")
    except Exception as e:
        log.warning(f"[retro-gen] {pname}: write failed for {rel_path}: {e}")
        return False

    # Commit + push to origin/main. Mirrors post_doc minus the
    # agent-feedback dance — single file, single commit.
    _chmod_workspace_via_alpine(working_dir, pname)

    def _run(cmd: list[str], **kw) -> _sp.CompletedProcess:
        timeout = kw.pop("timeout", 120)
        return _sp.run(cmd, cwd=working_dir, capture_output=True,
                       text=True, timeout=timeout, **kw)

    _run(["git", "fetch", "origin"])
    co = _run(["git", "checkout", "-B", "main", "origin/main"])
    if co.returncode != 0:
        log.warning(f"[retro-gen] {pname}: git checkout main failed — {co.stderr.strip()[:200]}")
        return False
    _run(["git", "add", rel_path])
    cached = _run(["git", "diff", "--cached", "--quiet"])
    if cached.returncode == 0:
        # Identical retro already committed (re-run idempotency).
        log.info(f"[retro-gen] {pname}: nothing to commit for sprint #{sprint_id}")
    else:
        commit_msg = f"retro: sprint #{sprint_id} retrospective [retro-gen]"
        commit_r = _run(["git", "commit", "--no-verify", "-m", commit_msg])
        if commit_r.returncode != 0:
            log.warning(f"[retro-gen] {pname}: git commit failed — {commit_r.stderr.strip()[:200]}")
            return False
        push_r = _run(["git", "push", "--no-verify", "origin", "main"], timeout=180)
        if push_r.returncode != 0:
            log.warning(f"[retro-gen] {pname}: git push failed — {push_r.stderr.strip()[:200]}")
            return False
        log.info(f"[retro-gen] {pname}: pushed retro doc for sprint #{sprint_id}")

    # Sign off retro_done in the PM API
    try:
        with httpx.Client(base_url=PM_API_URL, timeout=10) as client:
            r = client.post(
                f"/api/sprints/{sprint_id}/sign-off",
                json={"gate": "retro_done", "value": True,
                      "retro_doc_path": rel_path,
                      "notes": "Auto-generated by retro template (Phase 3)"},
            )
            if r.status_code >= 300:
                log.warning(
                    f"[retro-gen] {pname}: sign-off failed: HTTP {r.status_code} {r.text[:200]}"
                )
                return False
    except Exception as e:
        log.warning(f"[retro-gen] {pname}: sign-off error: {e}")
        return False

    log.info(f"[retro-gen] {pname}: sprint #{sprint_id} retro complete")
    return True
